numero = int(input('coloque um numero de 1 a 10 para a tabuada: '))

print(f'Aqui esta a tabuada de {numero}: ')
print(f'1 X {numero} = {numero*1}')
print(f'2 X {numero} = {numero*2}')
print(f'3 X {numero} = {numero*3}')
print(f'4 X {numero} = {numero*4}')
print(f'5 X {numero} = {numero*5}')
print(f'6 X {numero} = {numero*6}')
print(f'7 X {numero} = {numero*7}')
print(f'8 X {numero} = {numero*8}')
print(f'9 X {numero} = {numero*9}')
print(f'10 X {numero} = {numero*10}')